# Generated by Django 4.1.6 on 2023-02-12 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnailimage',
            name='thumbnail_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.thumbnail'),
        ),
    ]
