# Generated by Django 4.1.6 on 2023-02-13 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_thumbnailimage_thumbnail_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expiredlinkimage',
            old_name='id',
            new_name='uuid',
        ),
        migrations.AddField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
