# Generated by Django 4.1.6 on 2023-02-13 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_id_expiredlinkimage_uuid_image_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredlinkimage',
            name='duration',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(30000), django.core.validators.MinValueValidator(300)]),
        ),
    ]
