# Generated by Django 4.1.6 on 2023-02-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_expiredlinkimage_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnailimage',
            name='original_image',
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnails',
            field=models.ManyToManyField(to='core.thumbnailimage'),
        ),
    ]
